#!/usr/bin/env python
"""Generate src/core/omnivoice_lang_table.h from OmniVoice's lang_map.py.

The OmniVoice prompt carries the target language as a literal string between
``<|lang_start|>`` and ``<|lang_end|>``, and the model was trained on the ISO
639-3 IDs in ``omnivoice/utils/lang_map.py`` -- not on English names and not on
BCP-47 tags. ``OmniVoice.generate()`` runs every user-supplied value through
``_resolve_language()`` before it reaches the prompt; we mirror that resolver in
``src/core/omnivoice_lang.h`` and generate its table here so the two cannot
drift by hand-editing.

Usage:
    python tools/gen-omnivoice-lang-map.py                    # fetch upstream
    python tools/gen-omnivoice-lang-map.py --source lang_map.py
    python tools/gen-omnivoice-lang-map.py --check            # what CI runs
"""

import argparse
import ast
import pathlib
import sys
import urllib.request

UPSTREAM = (
    "https://raw.githubusercontent.com/k2-fsa/OmniVoice/main/"
    "omnivoice/utils/lang_map.py"
)

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parent / "src" / "core" / "omnivoice_lang_table.h"


def load_mapping(source: str) -> dict:
    """Pull LANG_NAME_TO_ID out of lang_map.py without importing it."""
    if source.startswith("http://") or source.startswith("https://"):
        text = urllib.request.urlopen(source).read().decode("utf-8")
    else:
        text = pathlib.Path(source).read_text(encoding="utf-8")

    tree = ast.parse(text)
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        if not any(
            isinstance(t, ast.Name) and t.id == "LANG_NAME_TO_ID"
            for t in node.targets
        ):
            continue
        # ast.literal_eval keeps this a data read, never an exec of the module.
        return ast.literal_eval(node.value)

    raise SystemExit(f"LANG_NAME_TO_ID not found in {source}")


def render(mapping: dict) -> str:
    # Sorted by name so the generated diff is reviewable and stable across runs;
    # the resolver builds its own hash indexes, so order carries no meaning.
    # Emitted unaligned on purpose: clang-format owns the layout of every
    # committed header, and a generator that padded columns would lose a
    # tools/format.sh --check fight with itself on the next regeneration.
    rows = sorted(mapping.items())

    lines = [
        "// AUTO-GENERATED by tools/gen-omnivoice-lang-map.py -- do not edit.",
        "//",
        "// Language name -> ISO 639-3 ID, mirrored from OmniVoice's",
        "// omnivoice/utils/lang_map.py (k2-fsa/OmniVoice, Apache-2.0). Names are",
        "// already lowercase upstream; the ID set is exactly the set of values, as",
        "// upstream's LANG_IDS = set(LANG_NAME_TO_ID.values()).",
        "//",
        "// Regenerate with: python tools/gen-omnivoice-lang-map.py",
        "",
        "#pragma once",
        "",
        "namespace core_omnivoice_lang {",
        "",
        "struct LangEntry {",
        "    const char* name; // lowercase English name",
        "    const char* id;   // ISO 639-3 code the model was trained on",
        "};",
        "",
        "inline constexpr LangEntry kLangTable[] = {",
    ]
    for name, code in rows:
        quoted = '"' + name.replace("\\", "\\\\").replace('"', '\\"') + '"'
        lines.append(f'    {{{quoted}, "{code}"}},')
    lines += [
        "};",
        "",
        f"inline constexpr int kLangTableN = {len(rows)};",
        "",
        "} // namespace core_omnivoice_lang",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--source", default=UPSTREAM, help="path or URL to lang_map.py")
    ap.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed header differs from a fresh render",
    )
    args = ap.parse_args()

    rendered = render(load_mapping(args.source))

    if args.check:
        if not OUT.exists():
            print(f"{OUT} is missing", file=sys.stderr)
            return 1
        if OUT.read_text(encoding="utf-8") != rendered:
            print(
                f"{OUT} is stale -- run tools/gen-omnivoice-lang-map.py",
                file=sys.stderr,
            )
            return 1
        print(f"{OUT.name}: up to date")
        return 0

    OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT} ({rendered.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
